---
ID: "1036928d-e4cf-4e3a-9e85-b8df601c53a1"
Parent: "3f205ea0-c23e-461d-a456-1af8101a0d8d"
Template: "3f205ea0-c23e-461d-a456-1af8101a0d8d"
Path: /sitecore/templates/Foundation/Recipes/Recipe/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210207T151959Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8aebf00e-e6c3-499d-9d36-d6a19a369dc1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "bdb92fd0-6dd4-4494-8b93-bbaed43043ee"
      Hint: Name
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210207T152003Z
