---
ID: "e7fc89df-0215-4510-b2c0-53acd4b09544"
Parent: "7c5500e0-f9ee-4bdf-bddf-8cb0d2c4c80f"
Template: "7c5500e0-f9ee-4bdf-bddf-8cb0d2c4c80f"
Path: /sitecore/templates/Feature/Basic Content/Hero Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210310T105106Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ca13bc56-e783-4cc7-8889-fbdb7491ae9e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210310T105110Z
