---
ID: "a4b9d9da-73e7-435f-91d5-9fe13ddddd25"
Parent: "f45a1951-bf9f-4535-85ab-feee0b5ce74f"
Template: "f45a1951-bf9f-4535-85ab-feee0b5ce74f"
Path: /sitecore/templates/Feature/Basic Content/Image List/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{469A5D5F-C02F-4942-BE1A-6EC722AC1A47}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210412T105430Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2464102f-5d44-4c97-94ab-2f3ae6af893f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210412T112134Z
