---
ID: "1aae5358-ebef-4b5e-b254-e3704abcfcea"
Parent: "8d2befb1-8277-4118-a4f2-62ee2cfbbd10"
Template: "8d2befb1-8277-4118-a4f2-62ee2cfbbd10"
Path: /sitecore/templates/Project/Blueprint/Page/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{1AE49D12-8DA1-4FBD-92FF-887B01C02BB5}">
        <r
          ds="{D3476E31-EDD4-4F6D-A058-8AB3CD579826}"
          id="{E97566F3-6FD4-4D9D-B537-4F466D537761}"
          par=""
          ph="blueprint-footer"
          uid="{C69A10E4-0105-47F7-A111-3839CBD321DE}"
          ccb="Clear on publish" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210310T161147Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0d9ed64e-6ea5-490d-bcac-96302922ffb8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210310T164446Z
